# Generated by Django 5.0.1 on 2024-02-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_chatmodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='userinput',
            field=models.TextField(),
        ),
    ]
