# Generated by Django 5.0.1 on 2024-02-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_chatmodel_userinput'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='response',
            field=models.TextField(null=True),
        ),
    ]
