# Generated by Django 5.0.1 on 2024-02-06 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_chatmodel_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmodel',
            name='response',
        ),
    ]
