# Generated by Django 5.0.1 on 2024-02-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_remove_chatmodel_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmodel',
            old_name='userinput',
            new_name='chathistory',
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='session_key',
            field=models.TextField(null=False),
        ),
    ]
