# Generated by Django 5.0.1 on 2024-02-09 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_rename_userinput_chatmodel_chathistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='session_key',
            field=models.TextField(),
        ),
    ]
