# Generated by Django 5.0.1 on 2024-02-09 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_chatmodel_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmodel',
            name='chathistory',
        ),
    ]
