# Generated by Django 5.0.1 on 2024-02-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_remove_chatmodel_chathistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='chathistory',
            field=models.JSONField(null=True),
        ),
    ]
